### PR TITLE
#37 - Added sass styling to convert generic pager into high-end pager.

### PR DESCRIPTION
**Pull request by Jimmy-Lin-91**
Summary of work done:
1. Hide all span children of .pager__item--previous, .pager__item--next, .pager__item--first, and .pager__item--last with visibility; none.
2. Created pseudo-elements with ::after for each hidden pager button.
3. Styled each pseudo-element to match the Figma design.
4. Switched from full pager mode to mini pager to double check work.
5. 
Screenshot 2023-11-16 at 10 48 53 AM

There will be no nav previous arrows when the user is on the first page as there will be no FAQ or content previous to the first page.

### CODE REVIEW

**Comment by PhillipLam89** [comment]
this is awesome and I can learn from this, I need to step up my CSS

**Comment by Jimmy-Lin-91** [comment]
> this is awesome and I can learn from this, I need to step up my CSS

Thank you, Phillip! Steal my code! You're eating up all the issues like Pac-Man.

**Comment by WaseemZ** [comment]
I agree this looks really good.

**Comment by ashabed** [comment]
*Chef's kiss* This looks great. Well done on a complicated task.

**Pull request merged**
